---
abstract: 'Logging to date/time stamped files (UNAUTHORIZED RELEASE)'
author:
  - 'Eric Cholet <cholet@logilune.com>, Karen Etheridge <ether@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 6.68, CPAN::Meta::Converter version 2.131490'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Log-Dispatch-File-Stamped
no_index:
  directory:
    - t
    - inc
requires:
  Log::Dispatch: 0
  Log::Dispatch::File: 2.38
  Path::Tiny: 0
  Test::More: 0.88
  Test::TempDir: 0
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Log-Dispatch-File-Stamped
  homepage: https://github.com/karenetheridge/Log-Dispatch-File-Stamped
  repository: https://github.com/karenetheridge/Log-Dispatch-File-Stamped.git
version: 0.11
