#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Log-Dispatch-File-Stamped
version:      0.02
version_from: Stamped.pm
installdirs:  site
requires:
    Log::Dispatch:                 0
    Log::Dispatch::File:           0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
