---
name: Log-Dispatch-File-Stamped
version: 0.04
author:
  - Eric Cholet <cholet@logilune.com>
abstract: Logging to date/time stamped files
license: perl
requires:
  Log::Dispatch: 0
  Log::Dispatch::File: 0
  Test::More: 0
provides: {}
generated_by: Module::Build version 0.2609
