---
abstract: 'Logging to date/time stamped files (UNAUTHORIZED RELEASE)'
author:
  - 'Eric Cholet <cholet@logilune.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.130880'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Log-Dispatch-File-Stamped
no_index:
  directory:
    - t
    - inc
requires:
  Log::Dispatch: 0
  Log::Dispatch::File: 2.38
  Path::Tiny: 0
  Test::More: 0.88
  Test::TempDir: 0
version: 0.10_006
